include: "rules/common.smk"

##### Target rules #####

rule all:
    input:
        "../../output/RNA_seq_FlowCellInfo.txt",
        # "PopulationSubstructure/ReferencePanel.vcf.gz",
        # "PopulationSubstructure/ReferencePanelMerged.vcf",
        # "MiscOutput/LowComplexityRegions.bed",
        # "PopulationSubstructure/out.relatedness2",
        # "MiscOutput/filtered.bcftools.stats",
        # "MiscOutput/filtered.bcftools.smplstats",
        # "MiscOutput/STAR_index/chrLength.txt",
        # expand("RNASeq/STAR/{sample}/Aligned.sortedByCoord.out.bam", sample=samples["sample"]),
        #"annotated/all.vcf.gz",
        config["gitinclude_output"] + "CountTable.SeparatedByFastq.tpm.txt.gz",
        config["gitinclude_output"] + "CountTable.tpm.txt.gz",
        config["gitinclude_output"] + "PopulationStructure/pca.eigenval",
        config["gitinclude_output"] + "PopulationStructure/pca.eigenvec",
        "PopulationSubstructure/plink/plink.eigenvec.var",
        # "qc/multiqc.html",
        # "MiscOutput/CallableSites.bed",
        # "genotyped/all.5.20000000-30000000.vcf",
        # expand("dedup_merged/{sample}.sorted.bam.bai", sample=samples["sample"]),
        # "filtered/all.vcf.gz",
        # "filtered/all.vcf.gz.tbi",
        # "MiscOutput/filtered.bcftools.stats",
        #"tables/calls.tsv.gz",
        #"plots/depths.svg",
        #"plots/allele-freqs.svg"
        # expand ( "PopulationSubstructure/Admixture/MergedForAdmixture.{K}.Q.pdf", K=config["PopulationSubstructure"]["AdmixtureK"] ),
        expand(config["gitinclude_output"] + "PopulationStructure/Admixture/MergedForAdmixture.{K}.Q.labelled", K=config["PopulationSubstructure"]["AdmixtureK"]),
        "eQTL_mapping/Misc/cis_gene_windows.bed",
        "eQTL_mapping/plink/ForAssociationTesting.snps.bed",
        "eQTL_mapping/plink/ForAssociationTesting.bed",
        "eQTL_mapping/plink/ForAssociationTesting.temp.fam",
        "eQTL_mapping/plink/ForAssociationTesting.bim",

##### Modules #####
include: "rules/make_test_data.smk"
include: "rules/mapping.smk"
include: "rules/RNASeqMapping.smk"
include: "rules/calling.smk"
include: "rules/populationstructure.smk"
#include: "rules/stats.smk"
include: "rules/eqtl_calling.smk"
include: "rules/qc.smk"
#include: "rules/annotation.smk"
